modLoader="javafml"
loaderVersion="[37,]"
issueTrackerURL="https://github.com/Darkhax-Minecraft/Death-Knell"
license="LGPL v2.1"

[[mods]]
modId="deathknell"
updateJSONURL="https://updates.blamejared.com/get?n=deathknell&gv=1.17.1"
version="${file.jarVersion}"
displayName="${modName}"
displayURL="${modHomepage}"
credits="${modCredits}"
authors="${modAuthor}"
description='''
${modDescription}
'''
itemIcon="minecraft:golden_apple"

[[dependencies.deathknell]]
    modId="forge"
    mandatory=true
    versionRange="[37,]"
    ordering="NONE"
    side="BOTH"

[[dependencies.deathknell]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"